[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }

[[language]]
name = "rust"
formatter = { command = "rustfmt" }
auto-format = true

[language-server.rust-analyzer.config.files]
watcher = "server"
